export { ACR_PREFIX, type SelectionHints, selectUpstream, type UpstreamDescriptor } from 'oidcraft'
export { type Broker, type BrokerConfig, createBroker } from './broker'
export { localSubject, pickClaims, renameClaims, standardClaims } from './claims'
export { type LinkOptions, type LinkResult, linkIdentity } from './link'
export { issuerOf, type UpstreamLogout, upstreamLogout } from './logout'
export type { BrokeredIdentity, ClaimMapper, FederationCallback, Handoff, LinkPolicy, UpstreamProvider } from './types'
